### ISSUE TITLE
Subscribing to /takktile/sensor_info causes the driver to crash

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/takktile_ros#1]
Running:

``` shell
$ rostopic echo -n1 /takktile/sensor_info
```

Causes the driver to crash with this error message:

```
Traceback (most recent call last):
  File "/home/mkoval/takktile-ws/src/takktile_ros/src/takktile_node.py", line 224, in <module>
    TakkNode(XYZ_MAP, FRAME_ID, TEMPERATURE_LOWPASS, CONTACT_THRESHOLD)
  File "/home/mkoval/takktile-ws/src/takktile_ros/src/takktile_node.py", line 124, in __init__
    info_pub.publish(frame_id, xyz_map, self.alive)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 847, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field indexes[] must be an integer type
```

**Comment by ClintLiddick** [comment]
Probably unknowingly broke in the previous commit. It works for me on latest, so pull and let me know.
